module.exports = {
    nametest: {
        hdr: 'Testing Tester',
        mke: 'mary',
        oai: '123456789',
        name: 'Jill Peterson',
        sex: 'f',
        race: 'w',
        height: '508',
        weight: '185',
        hair: 'blonde',
        offense: 'loitering',
        date: '04211987'
    },
    baddata: {
        hdr: '2',
        mke: '12',
        oai: '1234',
        name: 'Jill Peterson',
        sex: 'shi-tsu',
        race: 'turkish',
        height: '5',
        weight: '22',
        hair: 'red',
        offense: 'dui',
        date: '3/15/18'
    },
    testingLow: {
        hdr: '12345678',
        mke: 'A',
        oai: 'Junker01',
        name: '',
        sex: '',
        race: '',
        height: '20',
        weight: '',
        hair: 'Br',
        offense: 'DUI',
        date: '5/6/78',
        dl: '',
        dlst: 'B',
        dlex: '4/1987',
        lplat: 'BOOM',
        lpst: 'B',
        lyear: '87',
    },

    testingHigh: {
        hdr: 'Just a girl, standing',
        mke: 'EIOUY',
        oai: 'Junker001!',
        name: 'Just a girl, standing in front of',
        sex: 'Female',
        race: 'White',
        height: '1510',
        weight: '1510',
        hair: 'Strawberries',
        offense: 'Contributing to the delinquency',
        date: '05/06/1978',
        dl: '124-5678-91011-121314',
        dlst: 'Cali',
        dlex: '04/21/1987',
        lplat: 'I(heart)DOGS',
        lpst: 'Cali',
        lyear: '20019',
    },
    testingOutside: {
        hdr: 'MaryJane12345',
        mke: 'JXP1',
        oai: 'Junker02@',
        name: 'There is nothing I can do',
        sex: 'X',
        race: '2',
        height: '5ft',
        weight: 'HVY',
        hair: 'Ash 124',
        offense: '',
        date: 'May 6, 1978',
        dl: 'MaryMary123',
        dlst: 'C2',
        dlex: 'April,87',
        lplat: 'THX PAL',
        lpst: 'C2',
        lyear: 'RAVE',
    },

    testingInside: {
        hdr: '867530912345',
        mke: 'JXP-',
        oai: 'Junker003',
        name: 'Literally nothing',
        sex: 'F',
        race: 'W',
        height: '502',
        weight: '185',
        hair: 'Blonde',
        offense: 'Loitering',
        date: '05061978',
        dl: '150696828',
        dlst: 'WA',
        dlex: '04211987',
        lplat: '10THDOT',
        lpst: 'WA',
        lyear: '1987',
    },
    testingTwist: {
        hdr: 'auf weiderzehn',
        mke: 'J-XP1',
        oai: 'Junker',
        name: 'But I can play',
        sex: '2',
        race: 'J',
        height: '5-2',
        weight: '50K',
        hair: 'Blonde23',
        offense: 'Loitering x2',
        date: 'May61978',
        dl: 'Sorry, pal',
        dlst: 'H!',
        dlex: '04/21/87',
        lplat: 'ANY???',
        lpst: 'H!',
        lyear: '19RA',
    },

}
